### PR TITLE
dacScanV3.py now scans all DAC's by default

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Addresses #206 by rebasing off of @AndrewLevin's branch.

I've changed the default behavior of `dacScanV3.py` and `run_scans.py` such that when a DAC scan is launched if the `--dacSelect` parameter is *not* provided all DAC's are scanned.  If `--dacSelect` is provided only that DAC will be scanned.  

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Breaking change since if `--dacSelect` is not provided it will not prompt the user for an input but just scan all DACs.

## Motivation and Context

Because it was really tedious to scan DAC's individually and produced *a lot* of scandate subdirectories which required tracking multiple files and multiple analyses.

In retrospect all DAC's being scanned should have been the *nominal* behavior from the beginning.

## How Has This Been Tested?

See: 
- http://cmsonline.cern.ch/cms-elog/1073862
- http://cmsonline.cern.ch/cms-elog/1073827

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by AndrewLevin** [comment]
This implies changes to the analysis script, which currently assumes there is one DAC register scanned:

https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/develop/anaDACScan.py#L114

I guess I can rewrite it so that it will find all of the `dacSelect` values in the tree and then find the nominal values for each one, and the output text file will contain an extra column for the register name.

**Comment by bdorney** [comment]
> This implies changes to the analysis script, which currently assumes there is one DAC register scanned:
> 
> https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/develop/anaDACScan.py#L114
> 
> I guess I can rewrite it so that it will find all of the `dacSelect` values in the tree and then find the nominal values for each one, and the output text file will contain an extra column for the register name.

Yes I'm already working on it.  Try to focus on the PR's you already have open/issues assigned.

**Comment by jsturdy** [comment]
> Addresses #206 by rebasing off of @AndrewLevin's branch.

Is there a reason this was done?

**Comment by bdorney** [comment]
> > Addresses #206 by rebasing off of @AndrewLevin's branch.
> 
> Is there a reason this was done?

His PR was outstanding for over 20 days and it made sense to address #206 at the same time as these changes (@AndrewLevin already addressed #206 from what I saw).

**Comment by jsturdy** [comment]
Sorry, the question was why the `rebase` if `AndrewLevin/for_issue_206` was not the original parent (which is not clear from the PR)
Doing it this way now means you're not starting from the tip of the target branch, and that if anything in the previous PR/commits was objected to, it's now included here.  In this case it doesn't look like there will be any issues, but we should probably avoid this in the future, and instead just bump the review of a stale PR.

**Review by jsturdy — DISMISSED** [review]
seems ok

**Comment by bdorney** [comment]
I should be scolded...testing was done with `dacScanV3.py` which succeeded...testing was not done with `run_scans.py` which [fails](https://mattermost.web.cern.ch/cms-gem-daq/pl/yzd9esozepdd98kt6npftdmngo).  Not following my own rules #Bad.  Do not merge.

**Comment by bdorney** [comment]
Testing of `run_scans.py` shown here:

http://cmsonline.cern.ch/cms-elog/1074001

Test successful.

**Review by jsturdy — APPROVED** [review]

**Pull request merged**
