### PR TITLE
Re-write of run_scans.py incorporating new v3 tools

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Since the v3 calibration suite makes extensive use of AMC FW blocks that can only evaluate one optohybrid at a time, e.g.

- `VFAT_DAQ_MONITOR`,
- `SBIT_MONITOR`,
- Trigger counters,
 - etc...

And more importantly only one TTC stream is possible for all links (e.g. OHX and OHY cannot be receiving two different TTC streams from the AMC) parallelization of calibration scans is not really possible.

Additionally many new tools have made it into the calibration suite and it is somewhat annoying to be tracking by hand the storing of output data in "logical" locations. 

These facts have required a long overdue rewrite of `run_scans.py` for working with v3 electronics.

### Requirements
Requires:

- https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/157

### The New `run_scans.py` tool
Layout of this tool now follows the redone `sca.py` tool which uses multiple subparsers to take positional arguments which define a command to be executed.  Each command has in turn, it's own set of arguments.

#### Top Level Help Menu

```bash
% run_scans.py -h                                                            
usage: run_scans.py [-h] [-d]
                    
                    {dacScanV3,lat,monitorT,sbitMapNRate,sbitReadOut,sbitThresh,scurve,thrDac,trim}
                    ...

Arguments to supply to run_scans.py

positional arguments:
  {dacScanV3,lat,monitorT,sbitMapNRate,sbitReadOut,sbitThresh,scurve,thrDac,trim}
                        Available subcommands and their descriptions. To view
                        the sub menu call run_scans.py COMMAND -h
                        e.g. 'run_scans.py dacScanV3 -h'
    dacScanV3           Uses the dacScanV3.py tool to perform a VFAT3 DAC scan
                        on all unmasked optohybrids
    lat                 Launches an latency using the ultraLatency.py tool
    monitorT            Uses the monitorTemperatures.py tool to record
                        temperature data to a file until a KeyboardInterrupt
                        is issued
    sbitMapNRate        Uses the checkSbitMappingAndRate.py tool to
                        investigate the sbit mapping and rate measurement in
                        OH & CTP7 FPGA
    sbitReadOut         Uses the sbitReadOut.py tool to readout sbits
    sbitThresh          Launches an sbit rate vs. CFG_THR_ARM_DAC scan using
                        the sbitThreshScanParallel.py tool
    scurve              Launches an scurve using the ultraScurve.py tool
    thrDac              Launches an threshold using the ultraThreshold.py tool
    trim                Launches a trim run using the trimChamberV3.py tool

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           Print additional debugging information
```

#### Help Menu: `dacScanV3`

```bash
% run_scans.py dacScanV3 -h                                                  
usage: run_scans.py dacScanV3 [-h] [-e] [--isVFAT3A] cardName ohMask dacSelect

positional arguments:
  cardName         hostname of the AMC you are connecting too, e.g. 'eagle64'
  ohMask           ohMask to apply, a 1 in the n^th bit indicates the n^th OH
                   should be considered
  dacSelect        DAC Selection, see VFAT3 Manual

optional arguments:
  -h, --help       show this help message and exit
  -e, --extRefADC  Use the externally referenced ADC on the VFAT3.
  --isVFAT3A       State that you are scanning VFAT3a instead of VFAT3b
```

#### Help Menu: `lat`

```bash
% run_scans.py lat -h      
usage: run_scans.py lat [-h] [--amc13local] [-c CHAN] [--chMax CHMAX]
                        [--chMin CHMIN] [-i] [-m MSPL] [-n NEVTS]
                        [--randoms RANDOMS] [--scanmin SCANMIN]
                        [--scanmax SCANMAX] [-s SHELF] [--stepSize STEPSIZE]
                        [--t3trig] [--throttle THROTTLE] [-v VCAL]
                        [--vfatmask VFATMASK]
                        cardName ohMask

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered

optional arguments:
  -h, --help            show this help message and exit
  --amc13local          Use AMC13 local trigger generator
  -c CHAN, --chan CHAN  Channel on VFATs to run the latency scan. Only applies
                        when calling with --internal; otherwise OR of all
                        channels is used.
  --chMax CHMAX         Specify maximum channel number to scan
  --chMin CHMIN         Specify minimum channel number to scan
  -i, --internal        Run scan using calibration module
  -m MSPL, --mspl MSPL  Setting of CFG_PULSE_STRETCH register
  -n NEVTS, --nevts NEVTS
                        Number of events for each scan position
  --randoms RANDOMS     Generate random triggers using AMC13 local trigger
                        generator at rate specified
  --scanmin SCANMIN     Minimum CFG_LATENCY
  --scanmax SCANMAX     Maximum CFG_LATENCY
  -s SHELF, --shelf SHELF
                        uTCA shelf cardName is located in
  --stepSize STEPSIZE   Step size to use when scanning CFG_LATENCY
  --t3trig              Take L1A's from AMC13 T3 trigger input
  --throttle THROTTLE   factor by which to throttle the input L1A rate, e.g.
                        new trig rate = L1A rate / throttle
  -v VCAL, --vcal VCAL  Height of CalPulse in DAC units for all VFATs
  --vfatmask VFATMASK   If specified this will use this VFAT mask for all
                        unmasked OH's in ohMask. Here this is a 24 bit number,
                        where a 1 in the N^th bit means ignore the N^th VFAT.
                        If this argument is not specified VFAT masks are taken
                        from chamber_vfatMask of chamberInfo.py
```

#### Help Menu: `monitorT`

```bash
% run_scans.py monitorT -h
usage: run_scans.py monitorT [-h] [--extTempVFAT] [-t TIME] cardName ohMask

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered

optional arguments:
  -h, --help            show this help message and exit
  --extTempVFAT         Use external PT100 sensors on VFAT3 hybrid; note only
                        available in HV3b_V3 hybrids or later
  -t TIME, --time TIME  Time, in seconds, to wait in between readings
```

#### Help Menu: `sbitMapNRate`

```bash
% run_scans.py sbitMapNRate -h
usage: run_scans.py sbitMapNRate [-h] [-n NEVTS] [-r RATES] [-t TIME]
                                 [--vfatmask VFATMASK]
                                 cardName ohMask

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered

optional arguments:
  -h, --help            show this help message and exit
  -n NEVTS, --nevts NEVTS
                        Number of pulses for each channel
  -r RATES, --rates RATES
                        Comma separated list of floats that specifies the
                        pulse rates to be considered
  -t TIME, --time TIME  Acquire time per point in milliseconds
  --vfatmask VFATMASK   If specified this will use this VFAT mask for all
                        unmasked OH's in ohMask. Here this is a 24 bit number,
                        where a 1 in the N^th bit means ignore the N^th VFAT.
                        If this argument is not specified VFAT masks are taken
                        from chamber_vfatMask of chamberInfo.py
```

#### Help Menu: `sbitReadOut`

```bash
% run_scans.py sbitReadOut -h  
usage: run_scans.py sbitReadOut [-h] [--amc13local] [--fakeTTC] [-s SHELF]
                                [--t3trig] [--vfatmask VFATMASK]
                                cardName ohMask time

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered
  time                  time in seconds to acquire sbits for

optional arguments:
  -h, --help            show this help message and exit
  --amc13local          Use AMC13 local trigger generator
  --fakeTTC             Set up for using AMC13 local TTC generator
  -s SHELF, --shelf SHELF
                        uTCA shelf cardName is located in
  --t3trig              Take L1A's from AMC13 T3 trigger input
  --vfatmask VFATMASK   If specified this will use this VFAT mask for all
                        unmasked OH's in ohMask. Here this is a 24 bit number,
                        where a 1 in the N^th bit means ignore the N^th VFAT.
                        If this argument is not specified VFAT masks are taken
                        from chamber_vfatMask of chamberInfo.py
```

#### Help Menu: `sbitThresh`

```bash
% run_scans.py sbitThresh -h 
usage: run_scans.py sbitThresh [-h] [-a] [--series] [--scanmin SCANMIN]
                               [--scanmax SCANMAX] [--stepSize STEPSIZE]
                               [-t TIME] [--vfatmask VFATMASK]
                               cardName ohMask

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered

optional arguments:
  -h, --help            show this help message and exit
  -a, --arm             Use only the arming comparator instead of the CFD
  --series              Use the sbitThreshScanSeries.py tool instead; note the
                        scan will take much longer
  --scanmin SCANMIN     Minimum CFG_THR_ARM_DAC
  --scanmax SCANMAX     Maximum CFG_THR_ARM_DAC
  --stepSize STEPSIZE   Step size to use when scanning CFG_THR_ARM_DAC
  -t TIME, --time TIME  Acquire time per point in milliseconds
  --vfatmask VFATMASK   If specified this will use this VFAT mask for all
                        unmasked OH's in ohMask. Here this is a 24 bit number,
                        where a 1 in the N^th bit means ignore the N^th VFAT.
                        If this argument is not specified VFAT masks are taken
                        from chamber_vfatMask of chamberInfo.py
```

#### Help Menu: `scurve`

```bash
% run_scans.py scurve -h    
usage: run_scans.py scurve [-h] [--chMax CHMAX] [--chMin CHMIN] [-l LATENCY]
                           [-m MSPL] [-n NEVTS] [--vfatmask VFATMASK]
                           cardName ohMask

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered

optional arguments:
  -h, --help            show this help message and exit
  --chMax CHMAX         Specify maximum channel number to scan
  --chMin CHMIN         Specify minimum channel number to scan
  -l LATENCY, --latency LATENCY
                        Setting of CFG_LATENCY register
  -m MSPL, --mspl MSPL  Setting of CFG_PULSE_STRETCH register
  -n NEVTS, --nevts NEVTS
                        Number of events for each scan position
  --vfatmask VFATMASK   If specified this will use this VFAT mask for all
                        unmasked OH's in ohMask. Here this is a 24 bit number,
                        where a 1 in the N^th bit means ignore the N^th VFAT.
                        If this argument is not specified VFAT masks are taken
                        from chamber_vfatMask of chamberInfo.py
```

#### Help Menu: `thrDac`

```bash
% run_scans.py thrDac -h
usage: run_scans.py thrDac [-h] [--chMax CHMAX] [--chMin CHMIN] [-n NEVTS]
                           [--vfatmask VFATMASK]
                           cardName ohMask

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered

optional arguments:
  -h, --help            show this help message and exit
  --chMax CHMAX         Specify maximum channel number to scan
  --chMin CHMIN         Specify minimum channel number to scan
  -n NEVTS, --nevts NEVTS
                        Number of events for each scan position
  --vfatmask VFATMASK   If specified this will use this VFAT mask for all
                        unmasked OH's in ohMask. Here this is a 24 bit number,
                        where a 1 in the N^th bit means ignore the N^th VFAT.
                        If this argument is not specified VFAT masks are taken
                        from chamber_vfatMask of chamberInfo.py
```

#### Help Menu: `trim`

```bash
% run_scans.py trim -h  
usage: run_scans.py trim [-h] [--chMax CHMAX] [--chMin CHMIN] [-l LATENCY]
                         [-m MSPL] [-n NEVTS] [--trimPoints TRIMPOINTS]
                         [--vfatmask VFATMASK]
                         [--armDAC ARMDAC | --vfatConfig VFATCONFIG]
                         cardName ohMask

positional arguments:
  cardName              hostname of the AMC you are connecting too, e.g.
                        'eagle64'
  ohMask                ohMask to apply, a 1 in the n^th bit indicates the
                        n^th OH should be considered

optional arguments:
  -h, --help            show this help message and exit
  --chMax CHMAX         Specify maximum channel number to scan
  --chMin CHMIN         Specify minimum channel number to scan
  -l LATENCY, --latency LATENCY
                        Setting of CFG_LATENCY register
  -m MSPL, --mspl MSPL  Setting of CFG_PULSE_STRETCH register
  -n NEVTS, --nevts NEVTS
                        Number of events for each scan position
  --trimPoints TRIMPOINTS
                        comma separated list of trim values to use in
                        trimming, a set of scurves will be taken at each point
  --vfatmask VFATMASK   If specified this will use this VFAT mask for all
                        unmasked OH's in ohMask. Here this is a 24 bit number,
                        where a 1 in the N^th bit means ignore the N^th VFAT.
                        If this argument is not specified VFAT masks are taken
                        from chamber_vfatMask of chamberInfo.py
  --armDAC ARMDAC       CFG_THR_ARM_DAC value to write to all VFATs
  --vfatConfig VFATCONFIG
                        Specify file containing CFG_THR_ARM_DAC settings
```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

Parallelization is broken, all hail serial scans (in the future the calibration suite should be migrated into `cmsgemos` and use the full data path such that links can be scanned "in parallel").

## Motivation and Context

Summarized above.  Will be critical for 904 camp next week.

## How Has This Been Tested?

Testing performed in:
 - [elog#1](http://cmsonline.cern.ch/cms-elog/1067860): `dacScanV3`, `lat`, `monitorT`, and `sbitMapNRate` commands tested.
- [elog#2](http://cmsonline.cern.ch/cms-elog/1067944): `sbitReadOut`, `sbitThresh`, `scurve`, and `thrDac` commands tested.
- [elog#2]( http://cmsonline.cern.ch/cms-elog/1067972): `trim` command tested.

Usage examples illustrated in above elog.

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by jsturdy — APPROVED** [review]

**Review by BenjaminRS — COMMENTED** [review]
As I am not particularly familiar with it, what is the reason why the Travis CI build failed?

**Comment by bdorney** [comment]
> As I am not particularly familiar with it, what is the reason why the Travis CI build failed?

Yeah that's a good question, the issue is that the `Travis CI` right now is setup on an `env` for `slc6` instead of `cc7` and there `python` is 2.6, but we are using some list/dict comprehension syntax that was introduced in py2.7.  If you click on details and look you will see the py2.7 build succeeds; but the subsequent checks use the python 2.6 rpm.  I haven't figured out how to change this yet.

**Comment by BenjaminRS** [comment]
Ahh ok I see - thanks

**Review by BenjaminRS — APPROVED** [review]

**Comment by jsturdy** [comment]
> I haven't figured out how to change this yet.

The easiest would be to comment out the `slc6` job

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/19ed505e33ff483b0f570d041b6fdbfea50d5d1a/.travis.yml#L197-L199

and 

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/19ed505e33ff483b0f570d041b6fdbfea50d5d1a/.travis.yml#L223-L225

The better way would be to configure the `slc6` job to properly set up a `python2.7` environment

**Pull request merged**
