### PR TITLE
Maintenance: Remove old setup script and update instructions

### PR DESCRIPTION
**Pull request by bdorney**
The `setup/paths.sh` is outdated and should not be used now that packaging is done.

I've removed this script and updated the `README.md` to have the correct developer instructions for installation.

## Description

See above.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Maintenance

## Motivation and Context

With new developers participating we need to have more up-to-date instructions on using the package.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bdorney** [comment]
@BenjaminRS hope it's more clear now.

**Comment by BenjaminRS** [comment]
Forgot to say yes this should work. I was getting those prompts during installation from paths.sh. So removing them would indeed be helpful. Thanks.

**Comment by mexanick** [comment]
it is outdated at the moment. Please check whether it has been already addressed, and if not, rebase.

**Comment by bdorney** [comment]
rebase'd (again)

**Comment by mexanick** [comment]
@jsturdy do you think we still need this PR?

**Comment by jsturdy** [comment]
> @jsturdy do you think we still need this PR?

no

**Pull request closed without merging**
