### PR TITLE
WIP New Feature[V2b]: Addressing #142 Adding Options to run_scans.py and trimChamber.py

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Addressing: https://github.com/cms-gem-daq-project/vfatqc-python-scripts/issues/142

User was not able to specify `--L1Atime`, `--pulseDelay` or `--latency` to be used for the scurve scans launched by `trimChamber.py`.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

See comments: https://github.com/cms-gem-daq-project/vfatqc-python-scripts/issues/142

## How Has This Been Tested?

Testing is in progress: http://cmsonline.cern.ch/cms-elog/1017457

Will update once tests finish.

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsturdy** [comment]
@bdorney what's the status of this?
should it go into the upcoming release?

**Comment by bdorney** [comment]
PR is stale and would need to be rebased.  What's the timescale for the upcoming release?

**Comment by jsturdy** [comment]
Order of a day

**Comment by bdorney** [comment]
I will not have time to rebase and test this on that time scale.  It can either be closed or left open for the next release.

**Comment by jsturdy** [comment]
Superseded by #174

**Pull request closed without merging**
