### PR TITLE
Feature Request: Addressing #126, Filesystem Interaction Before Output Written

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Addressing: https://github.com/cms-gem-daq-project/vfatqc-python-scripts/issues/126

The following scans:
- `fastLatency.py`,
- `ultraLatency.py`,
- `ultraScurve.py`, and
- `ultraThreshold.py`.

Will now perform a filesystem interaction before writing the output file.  Should prevent data loss if `automount` of a NAS on a DAQ machine times out.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Data loss has been [reported](http://cmsonline.cern.ch/cms-elog/1008108) due to time out of `automount` of a NAS on a DAQ machine.

## How Has This Been Tested?

http://cmsonline.cern.ch/cms-elog/1008108
http://cmsonline.cern.ch/cms-elog/1009162

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsturdy** [comment]
Any update on whether this solution has alleviated the presumed issue?

**Comment by bdorney** [comment]
scandate=2017.09.13.16.45 which went overnight worked, http://cmsonline.cern.ch/cms-elog/100954

Previous scan where I tried this (2017.09.12.23.30, http://cmsonline.cern.ch/cms-elog/1009433) failed for a different reason (SCA issue).

So based on 2017.09.13.16.45 I think it's "working".  Or I just got lucky...launched another scan this morning.

**Review by cbravo135 — COMMENTED** [review]
I see you are running stat, but it doesn't seem like you look to see if it actually worked. As is, it doesn't seem like it does anything really. I would think the point of this is to catch if the FS is mounted or not if it isn't switch to write to /tmp or have some other way of recovering.

**Comment by bdorney** [comment]
The original idea that @jsturdy presented was that a filesystem interaction would trigger the `automount` so this would either:

- Work by default, or
- Cause `automount` to trigger ensuring the FS is mounted.

However, I think you raise a good point.  It might be worth checking the returncode of the command and then implementing a switch to:

1. Writing to a tmp directory
2. copying output from the tmp directory to the output data path

I think part of the problem also is that the output `TFile` is opened at the start of the scan so if the connection is lost maybe the `TFile` also becomes corrupted...suggest to move the initialization of the output `TFile` to just before the output `TTree` object is written.

**Comment by cbravo135** [comment]
I am just trying to think of this as a problem in general. We shouldn't be telling remote sites how to setup the FS on their machines but we can check and tell them something is wrong and make use of /tmp if we see a potential problem.

**Comment by jsturdy** [comment]
I suppose this hasn't moved due to other issues, or is there any sort of verification that any of these solutions are helping with the misbehaving setup?
Regarding the `TFile` initialization, it can be done in stages, i.e.,
* First `TFile(filename,"RECREATE")`, then close when operations are finished
* Next call `TFile(filename,"UPDATE")`, do new writes, saves, etc., then close

**Comment by jsturdy** [comment]
Closing as "On Hold" to ensure landscape queues don't trigger on pushes to this branch.  Reopen when ready for review

**Pull request closed without merging**
