### PR TITLE
[Bug fix] Trimming does not properly set VFAT ID in chamber config files

### PR DESCRIPTION
**Pull request by AndrewLevin**
This pull request updates the iterative trimmer so that it correctly sets the vfatID when running over multiple chambers.

## Description
Makes the `vfatIDval` a dictionary indexed by the optohybrid number.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
This bug was reported by @fsimone91 while running the trimming on QC8.

## How Has This Been Tested?
Yes, I tested it on the coffin (although it is only one chamber).

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jsturdy — DISMISSED** [review]

**Comment by jsturdy** [comment]
@AndrewLevin can you rebase and retarget this to the `release/legacy-2.7` branch?
It was recently created to help unify the legacy releasing, but hasn't yet been advertised widely.

**Comment by AndrewLevin** [comment]
Done.

**Review by lpetre-ulb — CHANGES_REQUESTED** [review]
Shouldn't line 497 and line 506 also be changed?

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/7af6aabe96138878f95e9a5faef1bc276092c3b4/iterativeTrim.py#L497

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/7af6aabe96138878f95e9a5faef1bc276092c3b4/iterativeTrim.py#L506

Seems that the fix was not propagated to all code paths.

**Comment by AndrewLevin** [comment]
Fixed.

**Review by lpetre-ulb — APPROVED** [review]

**Pull request merged**
