### PR TITLE
AMC13 control

### PR DESCRIPTION
**Pull request by jsturdy**
* added control of some AMC13 settings into the `ultraLatency` script

### CODE REVIEW

**Review by mexanick — COMMENTED** [review]
Should we add here enabling L1As at CTP7 (just as a cross-check)?

**Comment by jsturdy** [comment]
we could... though that's a simple thing to do on the CTP7
the AMC13 is the one that probably requires more intervention, and thus should be handled in the script

**Comment by jsturdy** [comment]
OK, added it in here, though it needs to be properly tested, this should make things simple for the QC8 setup as there *should* be no intervention needed on the CTP7

**Review by mexanick — APPROVED** [review]
Looks correct to me

**Pull request merged**
