### PR TITLE
Making develop even to master

### PR DESCRIPTION
**Pull request by mexanick**
Somehow a master went in front of the develop... Fixing it. No detailed review required as all has been reviewed for master
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Maintenance

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsturdy** [comment]
@bdorney wasn't there a set of PRs that was supposed to pull this hotfix into `develop` and `master`?
I don't see it currently open

@mexanick, please refrain from this type of PR in the future, the correct way is to apply the hotfix to both `master` and `develop` (as a hotfix is the **only** change allowed to go directly onto `master`)

**Comment by bdorney** [comment]
@jsturdy there was a set of pull requests.  I would have to cross-check the commit history to see which tracks where.  But for example commit 81f1fa5 was introduced into `master` in https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/182/commits this should match with commit bafd542 into develop introduced by https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/181/commits

**Comment by jsturdy** [comment]
Additionally, i don't see the `diff` that `github` is reporting (only the fixed `import`):
```diff
git diff -w -b gemdaq/master..gemdaq/develop ultraThreshold.py
diff --git a/ultraThreshold.py b/ultraThreshold.py
index ac141ce..eb9cde9 100755
--- a/ultraThreshold.py
+++ b/ultraThreshold.py
@@ -46,7 +46,7 @@ print startTime
 Date = startTime
 
 # Setup the output TTree
-from treeStructure import gemTreeStructure
+from gempython.vfatqc.treeStructure import gemTreeStructure
 gemData = gemTreeStructure('thrTree','Tree Holding CMS GEM VT1 Data')
 gemData.setDefaults(options, int(time.time()))
 
@@ -146,6 +146,7 @@ try:
         stopLocalT1(ohboard, options.gtx)
         pass
     else:
+        l1AInterval = -1
         if options.trkdata:
             setTriggerSource(ohboard,options.gtx,0x1)
             gemData.mode[0] = scanmode.THRESHTRK
```

**Comment by mexanick** [comment]
@jsturdy 

> @mexanick, please refrain from this type of PR in the future, the correct way is to apply the hotfix to both master and develop (as a hotfix is the only change allowed to go directly onto master)

I agree, but this happened already, that certain fixes were not submitted to develop...

**Comment by mexanick** [comment]
Colsing as outdated

**Pull request closed without merging**
